config/routes.rb
Normativepress::Application.routes.draw do
  resources :posts

  resources :users, :user_sessions, :books
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'books/:id/:slug' => 'books#show', :as => :book_slug
  match 'posts/:id/:slug' => 'posts#show', :as => :post_slug

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :book
  before_save :make_slug

  cattr_reader :per_page
  @@per_page = 25
	
	def make_slug
    if self.title.nil?
      self.slug = urlify(self.content[0..45])
    else
		  self.slug = urlify(self.title)
    end
	end

  def urlify(string)
    string = string.gsub(/[^\x00-\x7F]+/, '') # Remove anything non-ASCII entirely (e.g. diacritics).
    string = string.gsub(/[^\w_ \-]+/i, '') # Remove unwanted chars.
    string = string.gsub(/[ \-]+/i, '-') # No more than one of the separator in a row.
    string = string.gsub(/^\-|\-$/i, '') # Remove leading/trailing separator.
    string = string.downcase
    string.size.zero? ? random_permalink(string) : string
    rescue
    random_permalink(string)
  end

  def random_permalink(seed = nil)
    Digest::SHA1.hexdigest("#{seed}#{Time.now.to_s.split(//).sort_by {rand}}")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_filter :require_user, :except => [:index, :show]
  # GET /posts
  # GET /posts.xml
  def index
    @page = params[:page].to_i || 0
    @posts = Post.page(params[:page]).order("created_at DESC").includes(:book)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.where({:id => params[:id], :slug => params[:slug]}, :include => :book).first
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(post_slug_url(@post.id, @post.slug), :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(post_slug_url(@post.id, @post.slug), :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :post_type %><br />
   <%= f.select :post_type, options_for_select({ "Quote" => "quote", "Thoughts" => "thoughts"}) %>
  </div>
  <div class="field">
    <%= f.label :book %><br />
    <%= collection_select(:post, :book_id, Book.all, "id", "title") %>
  </div> 	
 	<%= f.hidden_field :user_id, :value => @current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
	<div id="post_<%= post.id %>" class="post">
		<div class="quote">
			<%= h post.content.html_safe %>
	  </div>
	  <div id="metadata_<%= post.id %>" class="metadata">
	  	<div class="book_meta">
			<% unless post.title.blank? %>
				<%= link_to post.title, post_slug_url(post.id, post.slug) %>
			<% else %> 
				<%= link_to "Imported Kindle Highlight", post_slug_url(post.id, post.slug) %>
			<% end %>
			 from <%= link_to post.book.title, book_slug_url(post.book.id, post.book.slug) %> by <%= h post.book.author %>, posted <%= time_ago_in_words(post.created_at) %> ago</div>
	  </div>
	  <% if @current_user %>
	 	<div class="admin_options">
	 		<%= link_to 'Show', post %>&nbsp;-&nbsp;<%= link_to 'Edit', edit_post_path(post) %>&nbsp;-&nbsp;<%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
	 	</div>
	  <% end %>
  </div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
	<%= render p %>
<% end %>
<br />

<% if @current_user %>
	<%= link_to 'New Post', new_post_path %>
<% end %>

<center><div class="pagination"><%= will_paginate @items %></div></center>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render @post %>